[package]
name = "loadme"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "loadme"
path = "src/loadme.rs"

[[bin]]
name = "run"
path = "src/run.rs"

[lib]
crate-type = ["cdylib"]
name = "loadme"
path = "src/loadme.rs"

[dependencies]
libc = "0.2.55"
